### PR TITLE
update to C 

### PR DESCRIPTION
**Pull request by iamreechi**

### CODE REVIEW

**Review by oluwatobiwilliams — COMMENTED** [review]
Hi Richie, just tested with this list of customer_id IN (21,33,40,910,911,1000,996,206,219 ).
The code still fails test cases 33, 40. 33 is not too obvious but have a look at the first payment date. It's duplicated. 
For 40, it duplicates the first payment and skips a month of payment before going onto the next plan. I stopped the review there but have a look at the other test cases I included above.

**Comment by iamreechi** [comment]
Hi Tobi, i just check all this and it’s working now. I guess there was
duplicates based on the union but all is fine. I am also open if you need
me to show you

**Review by oluwatobiwilliams — COMMENTED** [review]
Hi Richie, omo this code choke! It's almost done but test cases with customer_id IN (21,40) have some errors. For 21, there shouldn't be a reduction in amount paid even though the customer upgraded from [1,2]. The payments didn't occur in the same month.

For 40, similar, except that there's a payment date missing before the customer upgraded to plan_id 2. Have a look and if you still have some appetite to fix it, go for it.

**Comment by iamreechi** [comment]
Ok I will take a look at 21 and 40 and let you know

**Pull request merged**
